language: rust
rust: beta
sudo: false
env:
  global:
    - RUST_BACKTRACE=1
    - secure: "rd120SN+L18KUIbWloNk1SxlQdYikzVwRV/VR0+3hjMdhBM+L7EY0lDRBQVA8GX4flnn8iMNY072swMajizJ1elYgvo5NwhhUBaZcQ9rP6N0rl+DItkI6EYungQigE3ktSbYzKiEcDTT9viNCOw8+dZ8oDYT+EGxDgvDxq9MAUr+q1UHnU3CBhtKu/tDFzZeOUEqA5yOwBvMOL210RFnAsKx2Nvmzrfm8DaUPvjy5b4Z3vrY02eI4QwOWSPgbphgek41VPXyIO4ORxqtPNb1U/Rx2pDanGRlrApHM08nOKCyxqXLqwhy/fqcz8oJ9V+gkQGgkuj9WYIE2qqfU9Jlj8G0EBgUPc5DDd4iCL6b4MANNUivgczoghMMFeTagrBg0piP90cmZcI2WoKORNtB8JAZxd/45q56g4qLIsfMkXcytktX7Ou+JI7+a07d5C2VE3qewH7lk2w7rximO6ftBEkFmvMY5ZeBJE5N/2omkICkyX8UtGyWljZVRRm+lXCjPod4tDjTPR62X0NN6DjVKVwFE3LrqL7Ep+N2OIl/c8VfS/02vsPOqGn1U75rdW2qYT6ASDTXIQDiitbXryrpS5UBGFQdLNa+k1F6ULpohV1joZa2u2HSR0Pz0sHOxsH3OO7o2JSiPPulgvd4wiDNHs48AfIO3ga7rAi+vLYjR/I="
addons:
  firefox: latest
  chrome: stable
cache: cargo
install:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/cargo-generate || cargo install --vers "^0.2" cargo-generate)
  - cargo install-update -a
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
script:
  - wasm-pack build
  - wasm-pack test --chrome --firefox --headless
before_deploy:
  - (cd www && npm i && npm run-script build)
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages
  local-dir: www/dist
  verbose: true
  deployment-file: true

